### ISSUE TITLE
Idea: support partial document embedding

### ISSUE THREAD

**Issue by matthewwithanm** [gilbarbara/react-inlinesvg#1]
A way to specify that you only want a particular part of the document embedded. (This would be useful for spritesheets.)

We'd have to consider how this interacts with [fragment identifiers](http://www.broken-links.com/2012/08/14/better-svg-sprites-with-fragment-identifiers/) (it's certainly different as we would only be including part of the document) and [stacks](http://simurai.com/blog/2012/04/02/svg-stacks/) (more similar).

Currently, my thought is that a new prop could specify the classname for the group to include.

**Comment by gilbarbara** [comment]
I don't think this is relevant anymore.
