### ISSUE TITLE
Do not cache a failed get request

### ISSUE THREAD

**Issue by ssmereka** [gilbarbara/react-inlinesvg#100]
Just an idea for an enhancement.  Currently when setting `cacheGetRequests` to `true` a get request is only ever tried once.  To handle poor network connectivity and retries you could change this to when `cacheGetRequests` is `true` the request is only ever tried once if it was successful.

**Comment by gilbarbara** [comment]
Hey

There is a new version with support for title, description and custom props and an updated cache system.
Can you please try it? `npm i react-inlinesvg@next`
There are a few changes in props, you can check it [here](https://github.com/gilbarbara/react-inlinesvg/tree/next)

**Comment by Joroze** [comment]
Hi @ssmereka & @gilbarbara ,

I have implemented the following feature request here: https://github.com/gilbarbara/react-inlinesvg/pull/113.

The main push for this pull request was to actually resolve a bug that I believe I found. I'm not sure if it's exactly a bug or intended feature that was implemented, but I believe my changes would complement it.

**Comment by gilbarbara** [comment]
@ssmereka @Joroze 
I've refactored the cache system to immediately cache requests and exclude failed requests.
You can try it with:

```bash
npm i react-inlinescg@next
```

**Comment by Joroze** [comment]
@gilbarbara You should refactor the cache system from Array to Dictionary next to achieve that O(1) satisfactory 👍

**Comment by gilbarbara** [comment]
@Joroze Done! 🚀

**Comment by gilbarbara** [comment]
v1.0.0 released! 🎉
