### ISSUE TITLE
remove "isvg loaded" from list of classes on wrapper

### ISSUE THREAD

**Issue by bologer** [gilbarbara/react-inlinesvg#104]
> Expected behavior

Ability to overwrite `isvg loaded` classes on the `wrapper`

>Actual behavior

```js
<SVG src={selectFileSvg}
                     wrapper={React.createFactory('div')}
                     preloader={false}
                     className="test test-2"
                />
```

```html
<div class="isvg loaded test test-2">...</div>
```

>Steps to reproduce the problem

```js
<SVG src={selectFileSvg}
                     wrapper={React.createFactory('div')}
                     preloader={false}
                     className="test test-2"
                />
```

>React version

16.4.2

>React-Tooltips version

-

>Error stack

-

**Comment by gilbarbara** [comment]
The `loaded` class is an indicator that the file was successfully fetched.

**Comment by moisadoru** [comment]
The loaded fail/success situation can also be handled via the `onError` callback. In some projects, the hardcoded `loaded` classname, being too generic, applies unwanted css styles, and the lack of ability to suppress it, or control it, and the closure of this issue led to abandoning and looking for another library. Too bad.

**Comment by ahtcx** [comment]
@gilbarbara any chance on reconsidering this?

**Comment by gilbarbara** [comment]
@ahtcx try `npm i react-inlinesvg@next`
