### ISSUE TITLE
Add ability to specify custom attributes, e.g. title

### ISSUE THREAD

**Issue by bologer** [gilbarbara/react-inlinesvg#105]
>Expected behavior

Ability to add custom attribute, e.g. `title="Helleworld"`. 

Maybe if props is one of the non predefined, it could make it as attribute of `wrapper`.

e.g. onClick, etc. would be useful as well

```js
<SVG src={selectFileSvg}
                     wrapper={React.createFactory('div')}
                     preloader={false}
                     title="Some title"
                /> : ''}
```

> Actual behavior

Does not add custom attributes 

```html
<div class="isvg loaded">...</div>
```

>Steps to reproduce the problem

```js
<SVG src={selectFileSvg}
                     wrapper={React.createFactory('div')}
                     preloader={false}
                     title="Some title"
                /> : ''}
```

>React version

16.4.2

>React-Tooltips version

>Error stack

**Comment by rob2d** [comment]
+1

Also as corollary here cannot attach a `className` prop to SVG; instead it only styles the span surrounding things which is not a responsive way to handle this.

**Comment by danpoq** [comment]
A solution to add attributes or transform the SVG has been released in `0.8.4` 🎉

**Comment by gilbarbara** [comment]
On that note, I'm refactoring the code and removing the need for processing.

**Comment by gilbarbara** [comment]
@danpoq 
It's a complicated solution. I'll keep the processing for cases where the user needs to replace color or any other nested properties but adding a `title` and `description` props is simpler for users.
Also spreading the additional props on the SVG tag.

**Comment by gilbarbara** [comment]
Hey

There is a new version with support for title, description and custom props.
Can you please try it? `npm i react-inlinesvg@next`
There are a few changes in props, you can check it [here](https://github.com/gilbarbara/react-inlinesvg/tree/next)
