### ISSUE TITLE
Impending deprecation of componentWillMount lifecycle method in React 17

### ISSUE THREAD

**Issue by Wsiegenthaler** [gilbarbara/react-inlinesvg#106]
Just a heads up - React strict mode now warns that `InlineSVG` uses the soon to be deprecated lifecycle method `componentWillMount`:

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillMount: Please update the following components to use componentDidMount instead: InlineSVG

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Resolving this may require a more thorough review of the `InlineSVG` component. See [official blog post](https://reactjs.org/blog/2018/03/29/react-v-16-3.html) for details.

**Comment by cameron-martin** [comment]
Why did this get closed without being addressed?

**Comment by gilbarbara** [comment]
It's already fixed in the [next](https://github.com/gilbarbara/react-inlinesvg/tree/next) branch

**Comment by cameron-martin** [comment]
Ah cool, thanks for the info.
