### ISSUE TITLE
react-inlinesvg@0.8.4" has unmet peer dependency "prop-types@^15.0.0"

### ISSUE THREAD

**Issue by arturlagutin** [gilbarbara/react-inlinesvg#110]
>Expected behavior

No NPM warnings during installation.

>Actual behavior

warning " > react-inlinesvg@0.8.4" has unmet peer dependency "prop-types@^15.0.0".

>Steps to reproduce the problem

Try to install the package.

>React version

16.8.1

>React-Tooltips version

~

>Error stack

~

**Comment by gilbarbara** [comment]
Hey,

That's how peer dependencies [work](https://docs.npmjs.com/files/package.json#peerdependencies).
You need to install it in your project to avoid duplication.

**Comment by arturlagutin** [comment]
Why don't make it a bundled dependency, like it is done in many other packages? Not everyone uses PropTypes nowadays (Flow/TypeScript users for example), so I wouldn't consider it an essential package. Many people will hesitate to add it as a first-party dependency to their projects just to please `react-inlinesvg`.

**Comment by dylanpinn** [comment]
I agree with @arturlagutin, I think FB have recently updated the usage instructions for how to include `prop-types` [link](https://github.com/facebook/prop-types#how-to-depend-on-this-package).

I am currently using `flow` and would like to not have to include `prop-types` as an explicit devDependency if not needed in our project.
