### ISSUE TITLE
Support for inline script tags

### ISSUE THREAD

**Issue by mjamesderocher** [gilbarbara/react-inlinesvg#111]
I am trying to use a SVG with a script tag in it. The SVG code is taken from [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script#Example)

It has an onchange handler set on the circle, but when I click it, it thows the error that the function is undefined.

I am using version 0.8.4. 

I have also tried it with the "next" version, and the behavior is different. I get the error "Expected `onClick` listener to be a function, instead got a value of `string` type."

**Comment by gilbarbara** [comment]
hey,

Yeah, there's no support for the script tag inside an SVG to avoid XSS.
You can try [svgr](https://github.com/smooth-code/svgr) to convert your SVGs.

**Comment by JackCA** [comment]
it looks like inline script tags are in fact rendered now. Is that intentional?

**Comment by jamesopti** [comment]
> it looks like inline script tags are in fact rendered now. Is that intentional?

I came here to ask this. I want to prevent it!

@JackCA did you ever find a solution?
