### ISSUE TITLE
Svg should be unfocusable

### ISSUE THREAD

**Issue by Yvour** [gilbarbara/react-inlinesvg#112]
>Expected behavior
Rendered SVG should not be focusable while 'Tab' is clicked

>Actual behavior
It is focusable (in Internet Explorer 11)

>Steps to reproduce the problem
Add some svg element to the form which contains inputs with tabIndex property

>React version
16.6.3

>React-Tooltips version
3.4.3

>Error stack
No error stack, it just gets focus
The solution is to render the element with attribute
<svg focusable="false"></svg>
Current api does not allow to do it
https://stackoverflow.com/questions/18646111/disable-onfocus-event-for-svg-element

**Comment by gilbarbara** [comment]
Can you please try the `next` version?

```bash
npm i react-inlinesvg@next
```

**Comment by Yvour** [comment]
Sorry for not answering yet.
I have it just checked.

The 'svg' tag generated by react-inlinesvg of newest version gets following attributes.
+ xmlns
+ id
+ data-name
+ viewBox
+ class

So no '**focusable**' attribute.
'svg' tag generated with react-inlinesvg has _onLoad_ event so the solution that can be performed is add ref to the React element and add '**focusable**' attribute in this handler.
But it would be preferable to have this attribute added (focusable='false' added automatically or some custom attribute support)

**Comment by gilbarbara** [comment]
You probably can achieve that with the `preProcessor` prop.
