### ISSUE TITLE
Need a way to remove or hide <title> tag 

### ISSUE THREAD

**Issue by ajinkyawankhadeglobant** [gilbarbara/react-inlinesvg#114]
>Expected behaviour
There should be a way to show or hide that title

>Actual behaviour
Right now whenever we mouseover on any image the title display as file name. But what if we do not want to show title on mouse over.

>Steps to reproduce the problem
Mouse hover on any image

>React version

>react-inlinesvg version

>Error stack

**Comment by gilbarbara** [comment]
Can you please try the next version?

```bash
npm i react-inlinesvg@next
```
