### ISSUE TITLE
SVG is not a constructor function for JSX elements

### ISSUE THREAD

**Issue by valtism** [gilbarbara/react-inlinesvg#117]
I get the title error when trying to use the V1.0.0 library in the way defined in the README. I also get another error: `JSX element does not support attributes because it does not have a 'props' property`.

I'm not sure if these warnings are accurate, but I cannot compile with Storybook with these changes.

Apologies if I am seriously off the mark here. I'm extremely new to React and Typescript.

<img width="695" alt="Screen Shot 2019-07-19 at 17 05 05" src="https://user-images.githubusercontent.com/1286001/61516181-beae3a80-aa47-11e9-8e84-2199cbbd0764.png">

**Comment by gilbarbara** [comment]
Hey @valtism 
I need more information:
Are you using create-react-app or a custom webpack? Which typescript version?

**Comment by valtism** [comment]
This is not using create-react-app, we are using a custom Webpack. The Typescript version is 2.9.2

**Comment by gilbarbara** [comment]
My suggestion is to upgrade some packages. It could be `@types/react` or the `typescript` itself.

**Comment by valtism** [comment]
It does seem to be somewhat involved with `@types/react` but I can't seem to pin it down in our repository. I can confirm that it works with `create-react-app`.

**Comment by gilbarbara** [comment]
Alright! I'm closing this issue since there's not much else I can do.
Good luck!

**Comment by gencer** [comment]
@gilbarbara This only happens on `>= 1.0.0`. `0.8.4` has no issues. I downgraded to 0.8.4 for now.

Using Typescript `latest` version. Extension interfere with something else or something is wrongly coded -i don't know for sure-. Can you check this please?

P.S.: This is already ongoing rails project but not a project created via `create-react-app`

**Comment by gilbarbara** [comment]
@gencer I already checked this...
Please post the versions of react, @types/react and typescript

**Comment by gilbarbara** [comment]
@valtism @gencer Please try 1.1.2 and let me know if it works

**Comment by gencer** [comment]
@gilbarbara Sorry for late reply. I was going to post versions, however, I tested against `1.1.2` and it works!

Thank you so much for this extension and your fast help!

❤🎉

**Comment by valtism** [comment]
Oh, forgot to comment on this, but this fix did work and we now have this in production! Thanks @gilbarbara!!
