### ISSUE TITLE
After 1.0 def style is stripped off of elements

### ISSUE THREAD

**Issue by SimoneIrato** [gilbarbara/react-inlinesvg#118]
After upgrading to 1.0 svg's aren't properly loaded anymore.

Inside defs for example, fills and strokes are removed from the elements.
After some debugging it looks like dom-to-react is the culprit stripping so called "not recognized" attributes, resulting in elements rendered without those attrs.

https://github.com/gilbarbara/react-inlinesvg/blob/master/src/index.tsx#L257

At this point node contains all the proper attributes but looking at the result of prepareNode the same attributes are not present on related React node.

**Comment by gilbarbara** [comment]
Hey @SimoneIrato 
I've already identified this problem and I 'm working on a fix.
Can you post the SVG source code here so I can use it do test?

**Comment by gilbarbara** [comment]
Can you please try version 1.1.0?
Let me know if it fixes.

**Comment by SimoneIrato** [comment]
Hi, unfortunately it's still not working.
Here's a sample from the svg
`
<svg xmlns="http://www.w3.org/2000/svg" 
   version="1.1" 
   xmlns:xlink="http://www.w3.org/1999/xlink" 
   preserveAspectRatio="xMidYMid meet" 
   x="0px" 
   y="0px" 
   viewBox="-20 0 300 120">

   <style type="text/css">
    .prova_font{font-family:sans-serif;letter-spacing:0px;word-spacing:0px;font-size:9px;}
    .prova_path{stroke:black; stroke-width:1.5; stroke-linejoin:round; stroke-linecap:round;stroke-miterlimit:3; fill:none}
   </style>

   <defs>
      <symbol id="prova1" 
         overflow="visible">
         <g transform="translate(-11 -5.5)">
            <rect x="0" 
               y="0" 
               width="22" 
               height="11" 
               style="fill:#000000;"/>
            <rect x="-1" 
               y="4" 
               width="24" 
               height="3" 
               style="fill:#FFFFFF;"/>
         </g>
      </symbol>
   </defs>

   <g id="prova_group" 
      class="prova_font">
      
      <line x1="110" 
         y1="40" 
         x2="110" 
         y2="81" 
         class="prova_path"/>
      <use xlink:href="#dc" 
         x="110" 
         y="40"/>
      <use xlink:href="#ground_2s" 
         x="110" 
         y="85"/>
      <use xlink:href="#prova1" 
         x="110" 
         y="65"/>
   </g>
</svg>
`

**Comment by gilbarbara** [comment]
Hey,
Can you create a demo of what's expected in codesandbox?

This is what is rendered when I drag your SVG to Chrome.

![svg-test](https://user-images.githubusercontent.com/31954/61610332-3c806a80-ac2f-11e9-84cc-5f0355e578f6.png)

Your file reference other 2 symbols that don't exist in this file. Are these symbols that don't render?
When I tried to load the file with this package I got the same visual elements as the file.

**Comment by gilbarbara** [comment]
This is what got with this package:
![rendered](https://user-images.githubusercontent.com/31954/61610850-a6e5da80-ac30-11e9-93f3-80a12415b635.png)

Pretty much the same...

**Comment by SimoneIrato** [comment]
Thank's for pointing that out, at this point I'm afraid that's a webpack loader configuration removing the attributes.
I'll keep searching and keep posted if I found anything new.

**Comment by gilbarbara** [comment]
Are you using the image-webpack-loader? Configure it to skip some of the svgo's plugins or disable it completely to test.

```js
{
  test: /\.(jpe?g|png|gif|svg|ico)$/i,
  use: [
    {
      loader: 'file',
      query: { name: 'media/[name].[ext]' },
    },
    {
      loader: 'image-webpack',
      query: {
        svgo: {
          plugins: [{ removeViewBox: false }],
        },
      },
    },
  ],
},
```

**Comment by SimoneIrato** [comment]
I'm tryiing it just now, it's really strange.
* In the sandbox it's working fine.
* While upgrading i didn't change webpack configuration
* Downgrading works again
* I'm using Webpack 4, my configuration for svg is the following
```
{
        test: /\.svg$/,
        use: [
          {
            loader: 'svg-url-loader',
            options: { limit: 10 * 1024, noquotes: true },
          },
          {
            loader: 'image-webpack-loader',
            options: {
              disable: true,
              svgo: {
                disable: true,
              },
            },
          },
        ],
      },
```
* The svg is actually an api response so loading it from the project it's not really the right repro.
* Debugging step by step the 'style' attribute with the fills gets lost after the conversion in getElement method.

**Comment by gilbarbara** [comment]
By downgrading, you mean this package?
Have you tried with 1.1.1? I have fixed a bug with the style parsing.

Can you send the API response without passing it through webpack or this package?

**Comment by SimoneIrato** [comment]
Sorry I didn't try the 1.1.1 
Now it works like a charm as before!

**Comment by gilbarbara** [comment]
Awesome! :)
