### ISSUE TITLE
How Do Get <svg /> DOM Node Ref

### ISSUE THREAD

**Issue by zlanich** [gilbarbara/react-inlinesvg#124]
I need to get the ref to the SVG element itself to manipulate it. `ref={...}` currently returns the ref to the `<InlineSVG />` itself. How can I do this?

**Comment by gilbarbara** [comment]
Which version of this package?

**Comment by zlanich** [comment]
@gilbarbara 1.1.2 - I `yarn add`'d it a couple days ago.

**Comment by gilbarbara** [comment]
@zlanich 
I've added an `innerRef` prop in 1.1.5

👍

**Comment by zlanich** [comment]
@gilbarbara You're amazing. Thank you!
