### ISSUE TITLE
UniquifyIDs breaks data-urls

### ISSUE THREAD

**Issue by clentfort** [gilbarbara/react-inlinesvg#125]
When using `uniquifyIDs` any urls on `<image>`-elements will be broken as the unique-hash will be appended to the set URL. 

Since local ID references would start with `#` I propose a check is added to this line https://github.com/gilbarbara/react-inlinesvg/blob/master/src/index.tsx#L172 that tests if the value of the attribute starts with `#` if the attribute is a `href``

**Comment by gilbarbara** [comment]
The fix is on 1.1.6
Thanks!
