### ISSUE TITLE
Use Axios to enable authentication headers

### ISSUE THREAD

**Issue by diego-torres** [gilbarbara/react-inlinesvg#127]
I want to allow for headers configuration and other options like authenticating with the external resource, I think using Axios for the external request will be worth the try. Or by using the fetch, add a way to configure the request headers?

**Comment by gilbarbara** [comment]
You could do the request yourself and set the `src` with the response.
This library is just an SVG loader.

**Comment by RemyMachado** [comment]
Wouldn't that mean that we need to do an additional render?
The only way I see is using a `useEffect` to load a remote svg then doing a `setState` to set the response I feel like it's really inefficient.

Do you have something better @gilbarbara?

**Comment by gilbarbara** [comment]
Hey @RemyMachado 

You can set the `fetchOptions` prop.

Either way, a re-render is executed.
