### ISSUE TITLE
The sourcemaps point to source files that aren't included in the NPM distribution

### ISSUE THREAD

**Issue by MrJohz** [gilbarbara/react-inlinesvg#133]
The Typescript source files aren't included when I download the package from NPM.  However, they are referenced in the generated sourcemaps that are included.  This makes the sourcemaps largely useless, at least for consumers of the library.  The only way I'd be able to use them is if I downloaded the source files and manually inserted them into the right place, and if I've got to that stage, I may as well download the sourcemaps at the same time...

My suggestions would be:

* Include the Typescript source in the distributed files.  This is probably the easiest, and the files aren't particularly large.  There still wouldn't be any need to add the tests or other assorted files to the distribution.
* Include the sources inside the sourcemaps.  This is possible with some configuration, although I believe it's a bit of a faff, and it doesn't offer much over the previous option.
* Don't include the sourcemaps at all.  Given that they're not useful in their current form, they should be retained for debugging the source code in this repository, but they shouldn't be distributed.

Of these three options, the first is probably the best, as it makes the library generally more debuggable.  If you agree, I'm happy to create a pull request with the necessary changes to `package.json`.

**Comment by gilbarbara** [comment]
Hey,
It will be published in the next release

**Comment by MrJohz** [comment]
Thanks!
