### ISSUE TITLE
It's have text bug!

### ISSUE THREAD

**Issue by i-fuyun** [gilbarbara/react-inlinesvg#135]
I use a svg with react-inlinesvg in react. It's not show the text on the svg.
![error](https://user-images.githubusercontent.com/5111701/68736025-81833f00-061a-11ea-9068-ae8ac7bbac55.jpg)

But, the svg is OK when opened in chrome alone.
![ok](https://user-images.githubusercontent.com/5111701/68736030-87792000-061a-11ea-8ca4-13af1ec0f001.jpg)

svg (the s2.svg is in the  s2.zip package)
[s2.zip](https://github.com/gilbarbara/react-inlinesvg/files/3839539/s2.zip)
@gilbarbara

**Comment by gilbarbara** [comment]
I think it's fixed in version 1.2.0 (with react-from-dom 0.3.0 that handles the markup parsing)
