### ISSUE TITLE
Add className

### ISSUE THREAD

**Issue by pbn04001** [gilbarbara/react-inlinesvg#136]
Add a new className attribute, and this code
![image](https://user-images.githubusercontent.com/9288336/68982138-05782b00-07c3-11ea-9d73-0234d9068882.png)

Wasn't sure how to propose a PR to make this change
ERROR: Permission to gilbarbara/react-inlinesvg.git denied to pbn04001. Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

**Comment by gilbarbara** [comment]
ClassName is already pass down to the SVG.
