### ISSUE TITLE
It's have text bug also!

### ISSUE THREAD

**Issue by i-fuyun** [gilbarbara/react-inlinesvg#137]
I use a svg with react-inlinesvg in react. It's not show the text on the svg.
![image](https://user-images.githubusercontent.com/5111701/70603273-1d5f9500-1c31-11ea-811c-3bcffbc8563c.png)

The svg is OK when opened in chrome alone.
![image](https://user-images.githubusercontent.com/5111701/70603323-42540800-1c31-11ea-8768-4a40e4d824dc.png)

svg (the svg is in the .zip package)
[multimeter.zip](https://github.com/gilbarbara/react-inlinesvg/files/3949102/multimeter.zip)

@gilbarbara

**Comment by gilbarbara** [comment]
This is handled by react-from-dom. Feel free to submit a pull request in that repo.

**Comment by gilbarbara** [comment]
Anyway, I checked your file and it looks the same to me.
Which version are you using?

**Comment by gilbarbara** [comment]
@i-fuyun 
Anyway, I checked your file and it looks the same to me.
Which version are you using?

**Comment by i-fuyun** [comment]
> @i-fuyun
> Anyway, I checked your file and it looks the same to me.
> Which version are you using?

![image](https://user-images.githubusercontent.com/5111701/70677655-ba224100-1cca-11ea-9c0d-921a64e11ca1.png)
  "react": "^16.8.6",
 "react-dom": "^16.8.6",
   "react-inlinesvg": "^1.2.0",

But, when I use another SVG component(https://github.com/tanem/react-svg), the text is good.
PS: Because this react-svg component causes other problems, I didn't use it formally

**Comment by i-fuyun** [comment]
It's not  react-from-dom' bug.
Because  when I convert SVG attributes to react format, SVG display is normal.
![image](https://user-images.githubusercontent.com/5111701/71243700-d87fe080-234b-11ea-82f1-0ba02c8bb57f.png)

https://codesandbox.io/embed/distracted-galois-jlwjp?fontsize=14&hidenavigation=1&theme=dark
@gilbarbara
