### ISSUE TITLE
IE11 svg tag is empty

### ISSUE THREAD

**Issue by astranavt** [gilbarbara/react-inlinesvg#138]
In ie 11, react-inlinesvg inserts an empty svg tag

``` <svg xmlns="http://www.w3.org/2000/svg" class="myclass" />```
how to fix?

**Comment by gilbarbara** [comment]
It's impossible to know what's going on without seeing some code.
Please create a codesandbox or similar.

**Comment by astranavt** [comment]
in console 
Unable to get property 'Symbol(Symbol.iterator)_a.cgipohxhaet' of undefined or null reference
Could not convert the src to a React element

**Comment by gilbarbara** [comment]
@astranavt I can't know what's going on without seeing the code...

**Comment by astranavt** [comment]
https://codesandbox.io/s/nice-leaf-06fd2

**Comment by gilbarbara** [comment]
Codesandbox isn't loading in IE11, but I get it to work with IE11 in https://react-inlinesvg.stackblitz.io/

**Comment by astranavt** [comment]
> Codesandbox isn't loading in IE11, but I get it to work with stackblitz in https://react-inlinesvg.stackblitz.io/

how can I see the code?

**Comment by gilbarbara** [comment]
https://stackblitz.com/edit/react-inlinesvg
But there's nothing special about it.
`<SVG src={require('./logo.svg')} width={100} />`

**Comment by doxic012** [comment]
The code does not produce a valid dom element in IE using the 'react-from-dom' package at line 237:
![image](https://user-images.githubusercontent.com/3975568/71996915-59404700-323d-11ea-88c3-101ed281818e.png)

node is valid, element does not have any children though.

I've tested this with the following setup in typescript:
![image](https://user-images.githubusercontent.com/3975568/71997430-25195600-323e-11ea-956a-f652a53b430c.png)
(Sorry, the code blocks mess this up, so I used an image from np++)

Works in all other Browsers (Chrome, Edge Beta, Edge, Firefox).

**Comment by gilbarbara** [comment]
@doxic012 Please post an example at stackblitz or similar.

**Comment by doxic012** [comment]
https://stackblitz.com/edit/react-ts-qkg1nc?file=DynamicIcon.tsx

I put a debugger into the method used in the preProcessor.
Debug into the code ie11 with f11 until you get to the getElement()-Method, where the node is converted.

![image](https://user-images.githubusercontent.com/3975568/72076213-7cc6c880-32f5-11ea-8905-6c0a414e0d57.png)

In this case it results in an object does not support method "isNaN".
In our production system it does not throw an error, but the element variable simply does not have any children which results in an empty svg-tag instead of the fallback img being rendered.

![image](https://user-images.githubusercontent.com/3975568/72076271-910ac580-32f5-11ea-9e77-7a24246d40fb.png)

**Comment by gilbarbara** [comment]
@doxic012 The tag isn't empty, I can see the SVG on IE11

<img width="846" alt="ie-11" src="https://user-images.githubusercontent.com/31954/72123718-eae4ad00-3340-11ea-9a20-aa257c6aeccf.png">
<img width="456" alt="chrome" src="https://user-images.githubusercontent.com/31954/72123719-eae4ad00-3340-11ea-8115-038b0e0e7615.png">

**Comment by astranavt** [comment]
@gilbarbara 
https://stackblitz.com/edit/react-wjzq1v
<img width="935" alt="Снимок экрана 2020-01-10 в 10 17 16" src="https://user-images.githubusercontent.com/30686052/72133424-69b60600-3392-11ea-9f1c-9a5219046f9e.png">

**Comment by gilbarbara** [comment]
I see. I'll need a polyfill for `Number.isNaN` on IE.
I'll add to the README

**Comment by nsoeth** [comment]
I found the problem. Had the same problem and if I remove the

`uniquifyIDs={true}`

it works in IE11.
