### ISSUE TITLE
broken compatibility

### ISSUE THREAD

**Issue by fireflypie** [gilbarbara/react-inlinesvg#139]
Prior version of the package (prior to version 1) had a span class="isvg loaded" wrapper on top of the svg.

After the upgrade that wrapper is lost. I have used Styled-components to style every component in the project, even the icons, now all icons (and there are over 80 of imports are unstyled)

Example of an icon in the project.
```
`export const StyledIconContainer = styled.div`
  span {
    display: inline-block;
    margin-left: 6px;
    svg {
      width: 14px;
      height: 12px;
      & g {
        fill: #FFF !important;
      }
    }
  }
`;`
```

I will be creating a seperate component to add this wrapper back, but this gave me 1h-1.5h of extra unnecessary work. I think there should be a compatibility option.

**Comment by gilbarbara** [comment]
That's why it's a major version upgrade and it's described in the [release](https://github.com/gilbarbara/react-inlinesvg/releases/tag/v1.0.0) notes.
You can keep using 0.x versions anyway.
