### ISSUE TITLE
Is there a change log for updating to v2?

### ISSUE THREAD

**Issue by hankolsen** [gilbarbara/react-inlinesvg#149]
Hi!
I noticed that there was a version bump to 2.0.
Is there a change log available or any other information about potential breaking changes?

Best regards

**Comment by gilbarbara** [comment]
Hey @hankolsen 
I forgot to publish the release for 2.0! 🤫

https://github.com/gilbarbara/react-inlinesvg/releases/tag/v2.0.0

**Comment by hankolsen** [comment]
👍
