### ISSUE TITLE
Color a SVG path with id="abc"

### ISSUE THREAD

**Issue by ashishmundrajll** [gilbarbara/react-inlinesvg#154]
Hi All.

We have a SVG loaded in this viewer. Now when someone clicks a button outside viewer, we like to color SVG path where <path id="abc">. How can we achieve this?

Thanks,
Ashish

**Comment by gilbarbara** [comment]
Hey @ashishmundrajll 

This package just loads the files, it doesn't change the styles.
You can try adding a CSS class and change the path fill with it.
