### ISSUE TITLE
TypeError: src.match is not a function

### ISSUE THREAD

**Issue by beqramo** [gilbarbara/react-inlinesvg#157]
Hi, after updating to the react-script 4.0 and to react 17 this error appeared on my screen sadly.

![image](https://user-images.githubusercontent.com/40486471/98140950-7c7c6700-1edf-11eb-9cd6-02b00b5e6005.png)

**Comment by gilbarbara** [comment]
Hey @beqramo 

The error means the `src` isn't a string so it doesn't have the `match` method on its prototype. You need to make sure it is a string...

This most certainly isn't a problem with this package but something that has changed in CRA 4.0 which is a major upgrade...

Did you check CRA [changelog](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md)? Try to remove your node_modules and reinstall again as suggested.

**Comment by beqramo** [comment]
I did the same way as suggested but I see the same error again, have you tested it with CRA 4.0?

thanks for your aswer

**Comment by gilbarbara** [comment]
I didn't test it with CRA 4, but it doesn't matter.
The error is clear, src isn't a string.

**Comment by beqramo** [comment]
yes, I understand your point but my concern is that everything worked perfectly before updating so this is why I think that it isn't coming from me. if I had a time today I will check it on fresh CRA 4.0 project. thanks

**Comment by gilbarbara** [comment]
I don't think it's coming from your code but CRA 4.0 it's a major upgrade with breaking changes.

**Comment by beqramo** [comment]
do you have time to have a look at it?

**Comment by gilbarbara** [comment]
@beqramo 
Just tried it with a fresh CRA 4.0 instance and it's working ok.

Are you import the SVG from your project? CRA uses the [svgr](https://react-svgr.com/docs/webpack/)'s webpack loader that converts SVGs to react components, so you probably don't need this package for this case. 
Anyway, try to log the src you are passing to it and make sure it's a string. If it a React component, it will never work.

**Comment by gilbarbara** [comment]
@beqramo The demo is updated with react-scripts 4.0 and everything is working
