### ISSUE TITLE
Issue with React v17 and TypeScript

### ISSUE THREAD

**Issue by itsmdsameerkhan** [gilbarbara/react-inlinesvg#187]
'SVG' cannot be used as a JSX component.
  Its instance type 'InlineSVG' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.

**Comment by hesan-aminiloo** [comment]
Same here

**Comment by gilbarbara** [comment]
Duplicate of #181

**Comment by huytq03** [comment]
why this issue has closed like #181  but none of them have a solution?

**Comment by gilbarbara** [comment]
@huytq03

Because it is not a problem with this library.
Did you check [this](https://github.com/gilbarbara/react-inlinesvg/discussions/186)?

**Comment by huytq03** [comment]
> @huytq03
> 
> Because it is not a problem with this library. Did you check [this](https://github.com/gilbarbara/react-inlinesvg/discussions/186)?

fixed. tks
