### ISSUE TITLE
Unable to have the cache working

### ISSUE THREAD

**Issue by mlegait** [gilbarbara/react-inlinesvg#197]
**Describe the bug**
I'm not able to have the cache working. Even if the same URL is targeted, the same icon is downloaded again and again.

**To Reproduce**

Here is a piece of my component:
```jsx
import SVG from 'react-inlinesvg';
// [...]
  <SVG
    src={`${iconsBaseUrl}/${glyph}.svg`}
    title={alt}
    cacheRequests
    onLoad={(src, hasCache) => console.log(src, hasCache)}
    {...rest}
  />
```
So I've set `cacheRequests` to true. Confirmed in the Components tab of React DevTools:
![image](https://user-images.githubusercontent.com/19664438/197215484-f77c30ec-eed0-41ad-a7e5-10f9b94ea4c8.png)

But here is what I can see in the network tab of Chrome DevTools:
![Image_1021_1601_52](https://user-images.githubusercontent.com/19664438/197214499-74fdc9f2-b52d-4a32-aaf3-de54de9d6e48.png)
And here is what I can see in the console:
![image](https://user-images.githubusercontent.com/19664438/197214712-cae4f1b7-a873-49a3-8241-2913307ec3ac.png)
So `hasCache`is false.

**Expected behavior**
Each icon should be downloaded only once and cached so that they're not downloaded again.

Maybe it's just me not understanding how it's supposed to work. In that case, could you explain it to me? How can I check what's in the `cacheStore` you're talking about in the README?
Thank you very much for your help 🙏 

**Run `npx envinfo --system --binaries`**

```bash
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.41 GB / 15.81 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.1.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
```

```bash
$ yarn workspace @prosretail/elements info -R react-inlinesvg
└─ react-inlinesvg@npm:3.0.1
   ├─ Instances: 1
   ├─ Version: 3.0.1
   │
   └─ Dependencies
      ├─ exenv@npm:^1.2.2 → npm:1.2.2
      └─ react-from-dom@npm:^0.6.2 → npm:0.6.2
```

**Comment by gilbarbara** [comment]
Hey @mlegait 

The cache is for the session and not persistent between reloads.
You could set a rule in a service worker to add them to the Cache Storage, but this is beyond the scope of this library.

**Comment by mlegait** [comment]
Yes, sorry for the trouble. I misunderstood the behavior 😅 
Thank you for this library 🙏
