### ISSUE TITLE
Ts error: CacheProvider and SVG

### ISSUE THREAD

**Issue by jeffreyzzzs** [gilbarbara/react-inlinesvg#210]
I really want to use this library to cache some SVG files on cdn, but unfortunately, the ts error that also appeared on the demo appeared on my project, so I had to ask for help, thanks

![image](https://github.com/gilbarbara/react-inlinesvg/assets/52402138/2615eef8-b09a-4823-9fe4-87e61ac4812d)
![image](https://github.com/gilbarbara/react-inlinesvg/assets/52402138/fad24223-0b44-4491-b946-e0b714d7a6c7)

demo:
https://codesandbox.io/s/cool-cloud-9x94wt?file=/src/index.tsx:121-134

**Comment by gilbarbara** [comment]
Duplicate: https://github.com/gilbarbara/react-inlinesvg/issues/209

**Comment by jeffreyzzzs** [comment]
> 

Thanks so much!!
