### ISSUE TITLE
Title is not updated

### ISSUE THREAD

**Issue by steffenkleinle** [gilbarbara/react-inlinesvg#218]
### Describe the bug

Thanks for your work on this library! :heart: 

If title passed to the SVG component changes (because of a prop or state change), it is not updated. Instead, the old title keeps being rendered.

### Your minimal, reproducible example

https://codesandbox.io/s/frosty-breeze-w7kwhm

### Steps to reproduce

1. Got to the sandbox
2. Have a look at the title of the two svgs (`Old title`)
3. Click on the button `Click me!`
4. Have a look at the title of the two svgs (still `Old title`)

### Expected behavior

If the title passed to the SVG component changes, it should be updated accordingly.

### How often does this bug happen?

Every time

### react-inlinesvg version

4.0.4

### TypeScript version

5.2.2

**Comment by gilbarbara** [comment]
Hey @steffenkleinle 
Thanks! 🎉

Fixed in [4.0.5](https://github.com/gilbarbara/react-inlinesvg/releases/tag/v4.0.5)

**Comment by steffenkleinle** [comment]
Thanks @gilbarbara, that was by far the fastest fix and release I have seen so far! Amazing :heart_eyes:
