### ISSUE TITLE
Same firefox.svg file won't render from other CDN url

### ISSUE THREAD

**Issue by RavenHursT** [gilbarbara/react-inlinesvg#229]
### Describe the bug

I uploaded the same `firefox.svg` file that is used in the `react-inlinesvg` demo on `codesandbox.io`, put it up on an S3 cdn url, but when I try to use said url w/ `react-inlinesvg`, the library refuses to render the markup for the `<svg>`?

https://codesandbox.io/p/sandbox/inline-svg-not-working-cn5pyg?file=%2Fsrc%2FApp.tsx%3A32%2C40

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/inline-svg-not-working-cn5pyg?file=%2Fsrc%2FApp.tsx%3A32%2C40

### Steps to reproduce

1. take file
2. put it on cdn
3. try it

### Expected behavior

Should just render the image, even from other cdn urls

### How often does this bug happen?

Every time

### react-inlinesvg version

latest

### TypeScript version

latest

**Comment by gilbarbara** [comment]
Hey @RavenHursT 

It's a CORS problem, not something with the library itself.
It's on the [README](https://github.com/gilbarbara/react-inlinesvg#cors)
