### ISSUE TITLE
The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified

### ISSUE THREAD

**Issue by spassvogel** [gilbarbara/react-inlinesvg#232]
### Describe the bug

When using webpack 5.90.1 and trying to run my project with react-inlinesvg added, I get the following error

```
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve 'react/jsx-runtime' in '/project/node_modules/react-inlinesvg/dist'
  Parsed request is a module
  using description file: /project/node_modules/react-inlinesvg/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
```

A workaround is to add the following to the webpack.config

```
  resolve: {
    alias: {
      'react/jsx-runtime': 'react/jsx-runtime.js'
    },
  }
```

### Your minimal, reproducible example

none

### Steps to reproduce

Start a project with webpack  5.90.1, add react-inlinesvg as a dependency and build

### Expected behavior

As a user I expected this to work

### How often does this bug happen?

Every time

### react-inlinesvg version

4.1.3

### TypeScript version

4.9.5

### Build tool

webpack

**Comment by gilbarbara** [comment]
Hey @spassvogel 

The [demo](https://codesandbox.io/p/sandbox/github/gilbarbara/react-inlinesvg/) uses react-scripts (webpack under the hood) and didn't need any additional configuration, so it's not a problem with the library with webpack per se. So, probably something with your setup?

Anyway, nothing to do here.

**Comment by shalomscott** [comment]
I'm having the same problem and spent half a day looking for a workaround! Please look into this!

**Comment by spassvogel** [comment]
> I'm having the same problem and spent half a day looking for a workaround! Please look into this!

@shalomscott you can try the workaround mentioned in the opening description, but it's kinda sad we have to do webpack aliases to get packages to work.... 😔

**Comment by shalomscott** [comment]
Hey, quick reply! I'm in kind of a unique situation where I cannot edit the webpack config **at all**. So for now what I did was add this in my package.json (using yarn):
```json
{
  "resolutions": {
      "react-inlinesvg": "^3.0.1"
   }
}
```
Not at all ideal!
The line that webpack is complaining about is in `index.mjs` at the import: `import { jsx } from "react/jsx-runtime";`

See the relevant webpack docs here: https://webpack.js.org/configuration/module/#resolvefullyspecified

**Comment by gilbarbara** [comment]
Hey,

I changed the `jsx` option in the tsconfig to use the classic compilation in v4.1.4
Let me know if this works for you.
But please keep in mind that I'll drop React 16 support as soon as React 19 is released.
