### ISSUE TITLE
When persistent cache fails to open, icons infinitely load

### ISSUE THREAD

**Issue by peter-cardenas-ai** [gilbarbara/react-inlinesvg#234]
### Describe the bug

When [this call](https://github.com/gilbarbara/react-inlinesvg/blob/main/src/modules/cache.ts#L24-L25) to `caches.open` rejects, the icons that are subscribed stay in an infinitely loading state.

### Your minimal, reproducible example

Open in a non-secure context (`http`)

### Steps to reproduce

Make `caches.open` a function that rejects, and observer the behavior

### Expected behavior

The icons should still load

### How often does this bug happen?

Every time

### react-inlinesvg version

4.1.4

### TypeScript version

5.5.3

### Additional context

going to put up a pr to fix this since it seems like a simple fix

**Comment by gilbarbara** [comment]
Hey @peter-cardenas-ai 

I couldn't replicate it. I develop it using HTTP and never saw this problem.
Can you tell me how to replicate it?
