### ISSUE TITLE
svg not updating with state change

### ISSUE THREAD

**Issue by rheinheimer** [gilbarbara/react-inlinesvg#75]
I am using react-inlinesvg for a thumbnail image that should be updated if the underlying data generating that image changes. I only want to update the svg when the thumbnail is seen/mounted. When the state changes with the updated svg (a new url for the "src" attribute), I would expect the image also to change. However, I must do a page refresh to see the change.

Any thoughts? I'm thinking this is a bug, or perhaps an issue with react or html5, but it could also be with react-inlinesvg. And perhaps there is an immediate workaround I'm not thinking of.

**Comment by rheinheimer** [comment]
Apologies, but I realized it was my underlying svg source that was not changing. Closing, as I couldn't figure out how to delete this thread.

p.s. Thanks for the great component!

**Comment by gilbarbara** [comment]
@rheinheimer Oh, cool. I was about to take a look at this. I'll add tests for this anyway.
Thanks!
