### ISSUE TITLE
[Discussion] Don't load SVG through network but somehow inject it

### ISSUE THREAD

**Issue by Vadorequest** [gilbarbara/react-inlinesvg#77]
This is not an issue or feature request, but I'd like to explain an idea and see if it's actually doable.

I just discovered this repo because I wanted to display a SVG image in my app. I'm using create-react-app and had to look for workarounds in order to load SVG images as "Components". 

But I eventually found out (after successfully loading it as a component) that my SVG file was containing `<styles>`, and those styles weren't correctly imported, because they're not react friendly or something. (they were skipped during import, but displaying the SVG directly in a browser was working fine)

I made it work with `react-inlinsvg`, but then I rushed into another issue. Since we're loading the SVG file through network, it means it must be available on the network. But what I'm building is an app that is dedicated to be imported into another app, and so far my `build` folder only contains one JS and one CSS file, and I'd like to keep it that way to simplify deployment and maintenance.

But since I need the SVG to be available on the network, I must either:

1. Deploy the SVG file in addition of the JS/CSS, basically in an `assets` folder or alike, in the App that will contain my App.
2. Put the SVG file on a CDN and put a hard-coded path in my app, but that means another 3rd party tool, etc. (sounds overkill)

So, I was wondering if it wasn't possible to have a more elegant solution to this kind of issue. 
Since converting the SVG file as a react Component turns out bad (styles are skipped, etc.), but loading it through networks fixes the issue, would it be possible to load the SVG file, not load it as a react component, but as some kind of raw resource, that will be injected in the DOM when it needs to be displayed? If so, we would have the SVG within the app, it'd be bundled with the app and not be a separated resource, and it would display the same as if directly loaded by the browser.

But I don't know if that's possible. It would also fix the network latency issues, and avoid to have to use a Loader component. Any thoughts on this?

**Comment by gilbarbara** [comment]
hey,

You could try to convert the SVG to base64 and load it with this module.
Or edit the SVG tags to [React compatible](https://reactjs.org/docs/dom-elements.html) properties and load as a normal component.
