### ISSUE TITLE
Jest snapshots failing due to unique hash

### ISSUE THREAD

**Issue by nialloc9** [gilbarbara/react-inlinesvg#78]
Jest tests seem to be failing for every test that include react-inlinesvg due to the unique hash not matching. As the hash changes every time the test is run the snapshot does no match. Is there a way of testing this without breaking tests? Attached is an image of the failing snapshot test.

![screenshot from 2017-11-27 11-54-33](https://user-images.githubusercontent.com/14121652/33265640-582d1476-d36a-11e7-9010-6c52d09b06a8.png)

**Comment by gilbarbara** [comment]
Yes, using props.
You can turn hashing off with `uniquifyIDs` or pass your own hash with `uniquifyIDs`

**Comment by nialloc9** [comment]
Yes this was actually what I did earlier today to fix this but I was kind of hoping that there might be another solution out there that didn't involve changing the code to make the tests work. Even though it doesn't effect how the application runs and works perfectly well.

**Comment by gilbarbara** [comment]
I did update the minor version, that requires you to update it manually.

But I failed to mention the unique hash changes in the [0.7.0](https://github.com/gilbarbara/react-inlinesvg/releases/tag/0.7.0) release note, sorry.

**Comment by nialloc9** [comment]
Thats cool. Awesome job by the way.

**Comment by mackbrowne** [comment]
@gilbarbara this still seems to be adding a uniqueHash prop to my components :( . is it possible it isn't fixed yet?

**Comment by mackbrowne** [comment]
![screen shot 2018-01-31 at 4 43 58 pm](https://user-images.githubusercontent.com/1291776/35649204-55edbc96-06a6-11e8-8911-0b2e5bb80df5.png)

Here is a screenshot to show you jest is still failing even with the prop set to false.

**Comment by gilbarbara** [comment]
@mackbrowne fixed in 7f8dd862aa9b46c577ad4405436c5bdc288512e8
published as 0.7.5

**Comment by nialloc91** [comment]
@gilbarbara great work. Thank you.

**Comment by mackbrowne** [comment]
@gilbarbara thanks upgrading to 075 fixed it!
