### ISSUE TITLE
facing issue with new released 0.7.2

### ISSUE THREAD

**Issue by kishan-prolix** [gilbarbara/react-inlinesvg#81]
looking for modules in /home/kuldip/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /home/kuldip/node_modules/react-inlinesvg doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /home/kuldip/node_modules/react-inlinesvg.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
          /home/kuldip/node_modules/react-inlinesvg.jsx doesn't exist
        as directory
          /home/kuldip/node_modules/react-inlinesvg doesn't exist
      looking for modules in /home/kuldip/www/uk/node_modules
        using description file: /home/kuldip/www/uk/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/kuldip/www/uk/package.json (relative path: ./node_modules)
          using description file: /home/kuldip/www/uk/node_modules/react-inlinesvg/package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/kuldip/www/uk/node_modules/react-inlinesvg is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/kuldip/www/uk/node_modules/react-inlinesvg.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/kuldip/www/uk/node_modules/react-inlinesvg.jsx doesn't exist
            as directory
              existing directory
                use ./lib/index.js from main in package.json
                  using description file: /home/kuldip/www/uk/node_modules/react-inlinesvg/package.json (relative path: .)
                    Field 'browser' doesn't contain a valid alias configuration
                  after using description file: /home/kuldip/www/uk/node_modules/react-inlinesvg/package.json (relative path: .)
                    using description file: /home/kuldip/www/uk/node_modules/react-inlinesvg/package.json (relative path: ./lib/index.js)
                      no extension
                        Field 'browser' doesn't contain a valid alias configuration
                        /home/kuldip/www/uk/node_modules/react-inlinesvg/lib/index.js doesn't exist
                      .js
                        Field 'browser' doesn't contain a valid alias configuration
                        /home/kuldip/www/uk/node_modules/react-inlinesvg/lib/index.js.js doesn't exist
                      .jsx
                        Field 'browser' doesn't contain a valid alias configuration
                        /home/kuldip/www/uk/node_modules/react-inlinesvg/lib/index.js.jsx doesn't exist
                      as directory
                        /home/kuldip/www/uk/node_modules/react-inlinesvg/lib/index.js doesn't exist
                using path: /home/kuldip/www/uk/node_modules/react-inlinesvg/index
                  using description file: /home/kuldip/www/uk/node_modules/react-inlinesvg/package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /home/kuldip/www/uk/node_modules/react-inlinesvg/index doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /home/kuldip/www/uk/node_modules/react-inlinesvg/index.js doesn't exist
                    .jsx
                      Field 'browser' doesn't contain a valid alias configuration

**Comment by crohrer** [comment]
The problem seems to be caused by a missing lib directory - see https://github.com/gilbarbara/react-inlinesvg/commit/65d53b3bc65c9a2bf2d9b1a2a2c9d9adfd02a435#r26062567

**Comment by gilbarbara** [comment]
My bad! I forgot to add some NPM options to package.json
Please try 0.7.3 and let me know if it works.

**Comment by crohrer** [comment]
Now the module is found correctly when I run my dev-watcher, but my build-script throws this error:
```
Failed to minify the code from this file: 

        ./node_modules/react-inlinesvg/es/index.js:21 

Read more here: http://bit.ly/2tRViJ9
```

**Comment by Alex-Mann** [comment]
I am also getting this issue with create-react-app

**Comment by gilbarbara** [comment]
@crohrer @Alex-Mann 
I've identified a minor bug and I'm fixing now. I'll release a new version later tonight.

About the building failing, if you are using webpack 2 or 3, it will load the `module` field (if present) instead of `main` from package.json.
You can read more about it in the [documentation](https://webpack.js.org/configuration/resolve/#resolve-mainfields)

You have 2 options:
- change the `mainfields` in your webpack configuration to load `main` first.
- update your babel-loader to not exclude libraries with ES6+ code like the example below

```js
{
	test: /\.jsx?$/,
	loader: 'babel',
	query: {
		cacheDirectory: true,
	},
	exclude: /node_modules\/(?!([^/]+?\/){1,3}(src|es))/,
}
```

**Comment by gilbarbara** [comment]
I had to downgrade the babel options to not use `targets.node` after all.
The uglify that webpack uses don't support es6 and it would break create-react-app.
`module: es/index.js` now exports a semi-es6 version that works as usual in 0.7.4

Sorry about the mess. Too cutting edge. ⚡️
