### ISSUE TITLE
component renders my whole app instead of provided 'src' svg

### ISSUE THREAD

**Issue by akabab** [gilbarbara/react-inlinesvg#82]
Using version `0.7.4` & `create-react-app`

```
import React from 'react'
import SVG from 'react-inlinesvg'

const Loader = () => <div>Loading..</div>

const Maps = () => {
  return (
    <div id='Maps'>
      <SVG
        src='./logo.svg'
        preload={ <Loader /> }
        onLoad={ src => console.log('loaded!') }>
        failed
      </SVG>
    </div>
  )
}

export default Maps
```

![screen shot 2017-12-07 at 12 13 43](https://user-images.githubusercontent.com/6205705/33714844-60b11f12-db48-11e7-94d1-183d1be65be5.png)

I have no idea why it's rendering the whole React app inside the inlinesvg component.. any idea?

**Comment by gilbarbara** [comment]
Your server is probably giving a 404 page for the `./logo.svg` request and the SVG is just rendering it.
Make sure the svg file is available in the requested URL.

**Comment by akabab** [comment]
thanks

**Comment by arcticbarra** [comment]
@akabab How did you fix this?

**Comment by matthewwithanm** [comment]
@akabab It's an issue with your server. It can't find the svg at the path you're giving it.

@gilbarbara Do we not handle non-2xx responses or are the servers just returning 200s?

**Comment by gilbarbara** [comment]
@matthewwithanm Yes, we do. However most webpack setups, including create-react-app, usually responds with the index.html for all paths, so a router could handle it.
So 200 all around.

**Comment by matthewwithanm** [comment]
👍 awesome, thanks!
