### ISSUE TITLE
Using react-inlinesvg in an npm package

### ISSUE THREAD

**Issue by julianguyen** [gilbarbara/react-inlinesvg#91]
When I use react-inlinesvg in an npm package and add it to another project, I get this error. Any ideas how to resolve?

```
🚨  ../node_modules/react-inlinesvg/es/index.js: [BABEL] .../node_modules/react-inlinesvg/es/index.js: Unknown option: base.sourceMapRelative. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`
```

I tried setting .babelrc to 
```
{ "presets": ["react", "es2015"] }
```

**Comment by gilbarbara** [comment]
Not really.
Are you using it as a dependency in the other module? Or peerDependency? Which version?

It might be something about babel usually not been used to transpile node_modules but the es version is pretty much compatible with node 6+ and there's no sourcemap.

Try to load the `react-inlinesvg/lib` instead.
Switch the preset to `babel-preset-env`

Let me know if found out why this is happening.

**Comment by julianguyen** [comment]
@gilbarbara It's a dependency (the most recent version) in another module. Where would you load `react-inlinesvg/lib`? 

Thanks for your help!

**Comment by gilbarbara** [comment]
I don't how you are using it, so I can't say where...

**Comment by gilbarbara** [comment]
Nope
I think you are missing some babel transforms. Try to load the react preset.
Since this is an implementation problem, not related to this module, I'm closing this issue.

**Comment by julianguyen** [comment]
@gilbarbara I put
```
{
  "presets": ["env", "react", "es2015"]
}
```

But it doesn't work :/

**Comment by gilbarbara** [comment]
I can't know what's happening without seeing the whole thing.

**Comment by julianguyen** [comment]
Totally understand. Can't show it since it's private repo. Thanks for answering my questions!
