### ISSUE TITLE
Could we make the span wrapper optional and put the class in the SVG?

### ISSUE THREAD

**Issue by shukriadams** [gilbarbara/react-inlinesvg#94]
This isn't a bug, but a request for a feature.  It has already been addressed and closed in https://github.com/gilbarbara/react-inlinesvg/issues/4
but I figured I'd try my luck.

Would it be possible for us to render the SVG with that SPAN wrapper it currently has? Maybe with an optional attribute like 

    <InlineSVG className="myClass" src="mysource" nowrap=true />

 I know it might sound like nitpicking, but that SPAN just isn't doing anything other than carrying a classname which is meant for the SVG anyway. 

Also, I'm not that keen on @matthewwithanm's suggestion of using a css selector like .myclass > svg because this goes against BEM convention of keeping selectors as lean as possible. 

Pretty please?

**Comment by atav32** [comment]
Yeah I'm also running into unexpected alignment behavior with the `<span>` when the container is `display: flex`
