### ISSUE TITLE
Access node in onLoad handler

### ISSUE THREAD

**Issue by DavidSvetlik** [gilbarbara/react-inlinesvg#95]
Hi!

This library is very nice, thank you for it, but with inability to set various attributes its use is unnecessarily limited.

Would it be possible to add "component" (or "node" or whatever) parameter in onLoad handler which would provide access to newly created span component? Since there is no way to set width, height and other attributes I was thinking I would set them in onLoad event. But again, limits. :-(

Regards,
David S.

**Comment by danpoq** [comment]
A solution to add attributes or transform the SVG has been released in `0.8.4` 🎉

**Comment by gilbarbara** [comment]
Hey

There is a new version with support for title, description and custom props.
Can you please try it? `npm i react-inlinesvg@next`
There are a few changes in props, you can check it [here](https://github.com/gilbarbara/react-inlinesvg/tree/next)
