### ISSUE TITLE
TypeScript defs

### ISSUE THREAD

**Issue by Cristy94** [gilbarbara/react-inlinesvg#98]
Are there any TypeScript definitions for this module? I found none in the @types repository.

This is what I use so far, maybe the props should extend  `React.HTMLAttributes<HTMLDivElement>`

```
declare module 'react-inlinesvg' {
    export default class SVG extends React.Component<{
        src: string,
        id?: string,
        preloader?: JSX.Element,
        className?: string
        cacheGetRequests?: boolean,
        onLoad?: (src: string, isCached: boolean) => any,
        onError?: () => any,
    }, any> { }
}
```

**Comment by nickmccurdy** [comment]
I started a pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32238

**Comment by gilbarbara** [comment]
I'll create a local definition for the next major release

**Comment by nickmccurdy** [comment]
My pull request was merged and you can install `@types/react-inlinesvg`.

Typescript’s handbook recommends either using a separate declaration package like this or porting the original project to TypeScript. I wouldn’t recommend moving this declaration file into the original package without porting everything
